server:
  port: 8030

spring:
  datasource:
    url: jdbc:postgresql://localhost:5333/ticketingsystem
    username: Chanakya
    password: chanakya@123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

Simulation:
  event:
    EventCountMin: 2
    EventCountMax: 10
    PoolSizeMin: 400
    PoolSizeMax: 800
    TotalEventTicketsMin: 2000
    TotalEventTicketsMax: 4000
    EventCreationFrequencyMin: 120
    EventCreationFrequencyMax: 300
  customer:
    CustomerCountMin: 300
    CustomerCountMax: 500
    RetrievalRateMin: 5
    RetrievalRateMax: 20
    FrequencyMin: 10
    FrequencyMax: 30
  vendor:
    VendorCountMin: 15
    VendorCountMax: 30
    ReleaseRateMin: 100
    ReleaseRateMax: 200
    FrequencyMin: 20
    FrequencyMax: 45

ThreadTesting:
  event:
    EventCount: 10
    PoolSize: 1000
    TotalTicketCount: 10000
    EventCreationFrequency: 60
  customer:
    CustomerCount: 100
    RetrievalRate: 10
    Frequency: 1
  vendor:
    VendorCount: 5
    ReleaseRate: 40
    Frequency: 2